export const STATE_MACHINE_ARN = process.env.STATE_MACHINE_ARN;

export const ZENMONEY_API_BASE_URL = process.env.ZENMONEY_API_BASE_URL;
export const ZENMONEY_API_CONSUMER_KEY_PARAMETER_NAME = process.env.ZENMONEY_API_CONSUMER_KEY_PARAMETER_NAME;
export const ZENMONEY_API_CONSUMER_SECRET_PARAMETER_NAME = process.env.ZENMONEY_API_CONSUMER_SECRET_PARAMETER_NAME;
export const ZENMONEY_API_REDIRECT_URI = process.env.ZENMONEY_API_REDIRECT_URI;

export const ZENMONEY_TOKENS_TABLE_NAME = process.env.ZENMONEY_TOKENS_TABLE_NAME;
