export const USERS_TABLE_NAME = process.env.USERS_TABLE_NAME;

export const ZENMONEY_API_BASE_URL = process.env.ZENMONEY_API_BASE_URL;
export const ZENMONEY_API_CONSUMER_KEY_PARAMETER_NAME = process.env.ZENMONEY_API_CONSUMER_KEY_PARAMETER_NAME;
export const ZENMONEY_API_CONSUMER_SECRET_PARAMETER_NAME = process.env.ZENMONEY_API_CONSUMER_SECRET_PARAMETER_NAME;
export const ZENMONEY_API_REDIRECT_URI = process.env.ZENMONEY_API_REDIRECT_URI;
