export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

export const USER_POOL_CLIENT_CALLBACK_URL = process.env.REACT_APP_USER_POOL_CLIENT_CALLBACK_URL;
export const USER_POOL_CLIENT_ID = process.env.REACT_APP_USER_POOL_CLIENT_ID;
export const USER_POOL_DOMAIN = process.env.REACT_APP_USER_POOL_DOMAIN;

export const ZENMONEY_API_BASE_URL = process.env.REACT_APP_ZENMONEY_API_BASE_URL;
export const ZENMONEY_API_CONSUMER_KEY = process.env.REACT_APP_ZENMONEY_API_CONSUMER_KEY;
export const ZENMONEY_API_REDIRECT_URI = process.env.REACT_APP_ZENMONEY_API_REDIRECT_URI;
