openapi: 3.0.3

info:
  title: ZenMoney Backups
  contact:
    name: Danila Loginov
    email: danila@loginov.rocks
    url: https://loginov.rocks
  version: 0.0.0
  license:
    name: MIT
    url: https://github.com/loginov-rocks/ZenMoney-Backups/blob/main/LICENSE

externalDocs:
  description: GitHub
  url: https://github.com/loginov-rocks/ZenMoney-Backups

security:
  - UserPool: []

paths:
  /backups:
    get:
      summary: Backups - List
      tags:
        - Backups
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  backups:
                    type: array
                    items:
                      $ref: "#/components/schemas/Backup"
                required:
                  - backups
        401:
          description: Unauthorized
        500:
          description: Internal Server Error

  /backups/{fileName}:
    delete:
      summary: Backups - Delete
      tags:
        - Backups
      parameters:
        - name: fileName
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Server Error

  /backups/{fileName}/url:
    post:
      summary: Backups - Create URL
      tags:
        - Backups
      parameters:
        - name: fileName
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                required:
                  - url
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Server Error

  /zenmoney/auth:
    get:
      summary: ZenMoney - Validate Auth
      tags:
        - ZenMoney
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorized:
                    type: integer
                required:
                  - authorized
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Server Error
    post:
      summary: ZenMoney - Auth
      tags:
        - ZenMoney
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                zenMoneyAuthCode:
                  type: string
              required:
                - zenMoneyAuthCode
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
        502:
          description: Bad Gateway
    delete:
      summary: ZenMoney - Unauthorize
      tags:
        - ZenMoney
      responses:
        204:
          description: No Content
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Server Error

components:
  schemas:
    Backup:
      type: object
      properties:
        fileName:
          type: string
        serverTimestamp:
          type: integer
        size:
          type: integer
      required:
        - fileName
        - serverTimestamp
        - size

  securitySchemes:
    UserPool:
      bearerFormat: JWT
      scheme: bearer
      type: http
